### ISSUE TITLE
收藏列表无法正常显示

### ISSUE THREAD

**Issue by shardine** [pt-plugins/PT-Plugin-Plus#1292]
- PT 助手版本: v1.6.0.ba3d87e
- PT 助手安装方式：市场安装
- 浏览器名称及版本：edge
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：原本收藏列表里有数据，旧版本可以看到，新版本中选择‘待观看’和’全部‘收藏夹都显示没有任何数据。点’对比‘收藏夹可以正常显示

- 相关截图：
![image](https://user-images.githubusercontent.com/75930744/211206232-f380d61e-107b-413f-8ced-4674204b23d9.png)
![image](https://user-images.githubusercontent.com/75930744/211206392-6849897a-7921-428c-9797-ad8686df0a20.png)

- 重现步骤：
可能和收藏数量有关？

**Comment by fzlins** [comment]
是不是有自己添加的站点？

**Comment by shardine** [comment]
> 是不是有添加的自定义站点？

加过梓喵，但是我删掉以后还是没法显示

**Comment by fzlins** [comment]
> > 是不是有添加的自定义站点？
> 
> 加过梓喵，但是我删掉以后还是没法显示

能看到控制台（console）里的报错吗？

**Comment by shardine** [comment]
> > > 是不是有添加的自定义站点？
> > 
> > 
> > 加过梓喵，但是我删掉以后还是没法显示
> 
> 能看到控制台（console）里的报错吗？ 先试试actions里的最新版吧，应该已经适配了梓喵。

我检查了一下应该是之前梓喵变更地址导致的。收藏夹里收藏的那条记录还是原来的地址，有没有方法能在本地修改那条错误的数据？我在ptpp扩展的本地文件夹（C:\Users\用户名\AppData\Local\Microsoft\Edge\User Data\Default\Extensions\）里没找到收藏夹对应的数据

**Comment by fzlins** [comment]
> > > > 是不是有添加的自定义站点？
> > > 
> > > 
> > > 加过梓喵，但是我删掉以后还是没法显示
> > 
> > 
> > 能看到控制台（console）里的报错吗？ 先试试actions里的最新版吧，应该已经适配了梓喵。
> 
> 我检查了一下应该是之前梓喵变更地址导致的。收藏夹里收藏的那条记录还是原来的地址，有没有方法能在本地修改那条错误的数据？我在ptpp扩展的本地文件夹（C:\Users\用户名\AppData\Local\Microsoft\Edge\User Data\Default\Extensions\）里没找到收藏夹对应的数据

```
let data_key = 'PT-Plugin-Plus-Collection';
chrome.storage.local.get(data_key, (result) => {
  for( var i = 0; i < result[data_key]['items'].length; i++) { 
                         
    if (result[data_key]['items'][i]['link'] == 'https://******/details.php?id=22577') { 
      result[data_key]['items'].splice(i, 1);
      break;
    }
  }

  chrome.storage.local.set(result, () => {
    console.log('UPDATE');
  });
});
```

**Comment by shardine** [comment]
> > > > > 是不是有添加的自定义站点？
> > > > 
> > > > 
> > > > 加过梓喵，但是我删掉以后还是没法显示
> > > 
> > > 
> > > 能看到控制台（console）里的报错吗？ 先试试actions里的最新版吧，应该已经适配了梓喵。
> > 
> > 
> > 我检查了一下应该是之前梓喵变更地址导致的。收藏夹里收藏的那条记录还是原来的地址，有没有方法能在本地修改那条错误的数据？我在ptpp扩展的本地文件夹（C:\Users\用户名\AppData\Local\Microsoft\Edge\User Data\Default\Extensions\）里没找到收藏夹对应的数据
> 
> ```
> let data_key = 'PT-Plugin-Plus-Collection';
> chrome.storage.local.get(data_key, (result) => {
>   for( var i = 0; i < result[data_key]['items'].length; i++) { 
>                          
>     if (result[data_key]['items'][i]['link'] == 'https://******/details.php?id=22577') { 
>       result[data_key]['items'].splice(i, 1);
>       break;
>     }
>   }
> 
>   chrome.storage.local.set(result, () => {
>     console.log('UPDATE');
>   });
> });
> ```

用这个这个好像删不掉

<details>
<summary>点收藏夹的报错信息</summary>
<pre><code>
chunk-vendors.733ea339.js:7 
        
       TypeError: Cannot read properties of null (reading 'downloadMethod')
    at fn (chunk-e0dc2434.79f3ae6d.js:1:21359)
    at Object.i [as items] (chunk-vendors.733ea339.js:7:16568)
    at o.genFilteredItems (chunk-vendors.733ea339.js:254:1083)
    at o.genItems (chunk-vendors.733ea339.js:942:7712)
    at o.genTBody (chunk-vendors.733ea339.js:254:283)
    at o.render (chunk-vendors.733ea339.js:242:2558)
    at t._render (chunk-vendors.733ea339.js:7:23862)
    at o.i (chunk-vendors.733ea339.js:7:27903)
    at ii.get (chunk-vendors.733ea339.js:7:30788)
    at ii.run (chunk-vendors.733ea339.js:7:31521)
re @ chunk-vendors.733ea339.js:7
se @ chunk-vendors.733ea339.js:7
ne @ chunk-vendors.733ea339.js:7
t._render @ chunk-vendors.733ea339.js:7
i @ chunk-vendors.733ea339.js:7
ii.get @ chunk-vendors.733ea339.js:7
ii.run @ chunk-vendors.733ea339.js:7
Zn @ chunk-vendors.733ea339.js:7
(匿名) @ chunk-vendors.733ea339.js:7
ue @ chunk-vendors.733ea339.js:7
Promise.then(异步)
oe @ chunk-vendors.733ea339.js:7
ve @ chunk-vendors.733ea339.js:7
ei @ chunk-vendors.733ea339.js:7
ii.update @ chunk-vendors.733ea339.js:7
vt.notify @ chunk-vendors.733ea339.js:7
set @ chunk-vendors.733ea339.js:7
si.set @ chunk-vendors.733ea339.js:7
filterCollections @ chunk-e0dc2434.79f3ae6d.js:1
setGroupActive @ chunk-e0dc2434.79f3ae6d.js:1
ie @ chunk-vendors.733ea339.js:7
n @ chunk-vendors.733ea339.js:7
ie @ chunk-vendors.733ea339.js:7
In.t.$emit @ chunk-vendors.733ea339.js:7
click @ chunk-e0dc2434.79f3ae6d.js:1
ie @ chunk-vendors.733ea339.js:7
n @ chunk-vendors.733ea339.js:7
ie @ chunk-vendors.733ea339.js:7
In.t.$emit @ chunk-vendors.733ea339.js:7
click @ chunk-vendors.733ea339.js:1018
ie @ chunk-vendors.733ea339.js:7
n @ chunk-vendors.733ea339.js:7
Qs.r._wrapper @ chunk-vendors.733ea339.js:7
</code></pre>
</details>
