### ISSUE TITLE
馒头（mt）种子详情页，点击右侧下载报错，下载链接获取失败 code != 0

### ISSUE THREAD

**Issue by ziyuCat** [pt-plugins/PT-Plugin-Plus#1819]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [ x] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [ x] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [ x] 搜素过Issue，确认没有相关问题
- [ x] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本: 1.6.1.2614
- PT 助手安装方式：（市场安装，或zip包安装） crx 安装
- 浏览器名称及版本： Microsoft Edge 124.0.2478.51 （最新版）
- 浏览器是否安装了其他插件： 否
- 停用其他插件后是否正常工作：否
- 问题描述：
进入详情页，点击右侧下载，报错。

- 相关截图：
- 
![image](https://github.com/pt-plugins/PT-Plugin-Plus/assets/33019443/52358871-177b-4080-8010-1c642789ff4b)

-f 12 控制台信息
种子 579288 下载链接获取失败, code != 0 {"message":"key無效","data":null,"code":1}
content.js:1  Uncaught TypeError: Cannot read properties of undefined (reading 'data')
    at Object.resolveMTDownloadURL (content.js:1:35167)
    at Object.assign.PTService.resolveMTDownloadURL (content.js:1:29743)
    at App._getDownloadUrlByPossibleHrefs (eval at runScript (content.js:1:1), <anonymous>:24:24)
    at App.getDownloadURL (eval at runScript (content.js:1:1), <anonymous>:34:21)
    at Object.click (eval at runScript (content.js:1:1), <anonymous>:481:26)
    at HTMLAnchorElement.<anonymous> (content.js:1:24871)
    at HTMLAnchorElement.dispatch (jquery-3.3.1.min.js:2:41772)
    at y.handle (jquery-3.3.1.min.js:2:39791)

- 重现步骤：

**Comment by IITII** [comment]
换下 api token
